### PR TITLE
13145: Added csvs for cabled playback

### PR DESCRIPTION
**Pull request by PhilTran01**
I added csvs for cabled playback. The info was pulled from Google Sheets. I tried to match the info as much as I could when compared to the ingestion_csvs. I did not include deployment numbers for this since it wasn't given by the spreadsheet.

### CODE REVIEW

**Comment by danmergens** [comment]
Looks good to me, but I'd like Friedrich to review the content and make sure he's on board before we merge.

**Comment by PhilTran01** [comment]
I actually need to make a couple changes, I just noticed this morning that I forgot to take into account the commas in the directory glob, I will fix this and then push it back in.

**Comment by friedrichknuth** [comment]
Looks good. Will need to test it out.

**Comment by danmergens** [comment]
We don't have the port agent files available. When they are available, we need to be careful about having both sources listed or we could end up with duplicate data ingested into the system. Let's worry about the port agent sources when we have a defined source for them.

**Comment by danmergens** [comment]
@friedrichknuth - do you have further comments on this, or can we merge this commit?

**Pull request merged**
